### PR TITLE
Fix Floater Issues

### LINKED ISSUE #32: Fix floaters again.
The subpage nav is still not great.

### PR DESCRIPTION
**Pull request by zjr**
Fixes #32.

### CODE REVIEW

File: src/containers/Main.jsx [hunk 1]
```diff
@@ -103,101 +75,77 @@ export default class Main extends React.Component {
...
-    } else {
-      if (pageBox.bottom >= innerHeight * 0.7) {
-        mutateQueue.push(lockFloaterToMiddle(floater));
-      }
-      if (pathDiff) {
-        mutateQueue.push(lockFloaterToTop(getFloater(this.paths[this.activePath])));
-      }
-    }
+    const downward = this.scrollPos < scrollY;
+    const hideFloater = ref.box.bottom <= innerHeight * 0.6;
```
Comment (spurkalurk) [inline src/containers/Main.jsx]: where does this 0.6 number come from?

Comment (zjr) [reply src/containers/Main.jsx]: Trial & error.
